# -*- coding: utf-8 -*-
"""Periodictable.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NvCjSN32V_01kZSY1_k9Lbujju9C-4KQ
"""

!pip install periodictable

import periodictable

Atomic_No = int(input("Enter Element Atomic No: "))
element = periodictable.elements[Atomic_No]

print("Atomic number:", element.number)
print('Symbol:',element.symbol)
print('Name: ',element.name)
print('Atomic mas:',element.mass)
print('Density:', element.density)